### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Jiao-xxm** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#10]
大佬，数据集是怎么用的呀
可否在readme,md 中详细写一下，想学习一下

**Comment by PengfeiM** [comment]
这个是标准的VOC格式数据集，代码里面
https://github.com/PengfeiM/Fatigue-Driven-Detection-Based-on-CNN/blob/cfa4f9a029e1ec40edf0b73d8618cc1c557f803f/Train.py#L55
到
https://github.com/PengfeiM/Fatigue-Driven-Detection-Based-on-CNN/blob/cfa4f9a029e1ec40edf0b73d8618cc1c557f803f/Train.py#L61
之间是读取数据，
调用数据的时候是用的for循环：https://github.com/PengfeiM/Fatigue-Driven-Detection-Based-on-CNN/blob/cfa4f9a029e1ec40edf0b73d8618cc1c557f803f/Train.py#L80
img读取图片，target读取的目标框
