### ISSUE TITLE
txt.py里面的ssd_voc_5000_plus.pth文件

### ISSUE THREAD

**Issue by jdbsc** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#11]
这个文件是手动添加吗 要用哪个测试数据？

**Comment by PengfeiM** [comment]
txt.py?

**Comment by jdbsc** [comment]
sorry 不是txt 是test.py

**Comment by PengfeiM** [comment]
这个应该是训练好的权重文件

**Comment by jdbsc** [comment]
可是train.py 训练生成的文件格式为 ssd30_VOC_1000（迭代次数）.pth  没有ssd_voc_5000_plus.pth这种形式的

**Comment by jdbsc** [comment]
另外数据集中共有4000多张图片   为何eval.py输出时显示总共1283张
@PengfeiM

**Comment by PengfeiM** [comment]
1. **权重文件问题**
那可能是我改过代码，然后那一块后来没用就没改了。
2. **数据集问题**
因为4000多张图片一部分用来做训练集，一部分用来做测试集。    训练和测试的图片是随机选的，在数据集里面有个txt.py用来生成训练测试列表。自己可以调整比例。

**Comment by jdbsc** [comment]
好的

**Comment by jdbsc** [comment]
作者 我想问一下你CNN用的哪个模型

**Comment by PengfeiM** [comment]
> 作者 我想问一下你CNN用的哪个模型

ssd，
