### ISSUE TITLE
cuda不可用

### ISSUE THREAD

**Issue by wyy523141** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#15]
博主你好，我的电脑在运行程序时普遍出现了cuda不可用问题，再不安装cuda的情况下可以用别的方式统一解决这个问题吗

**Comment by PengfeiM** [comment]
1. 请问你的电脑显卡是N卡还是A卡？
2. N卡需要cuda来调用显卡计算，不用cuda的话只用CPU计算会比较慢。
3. 如果不确定你的GPU类型，可以下载一个[GPU-Z](https://www.techpowerup.com/gpuz/)来查看显卡参数和cuda等的支持情况。

**Comment by PengfeiM** [comment]
如果不想用cuda的话，可以在Config.py中把use_cuda设为false。
