### ISSUE TITLE
数据集检测

### ISSUE THREAD

**Issue by yrh943489219** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#16]
作者大大，请问camera模块可以不用吗，只想单纯的用数据集做检测可以吗，还有方便留一个联系方式吗，您的邮箱可能失效了

**Comment by PengfeiM** [comment]
可以啊。 
camera只是为了调用摄像头获取视频。
直接用视频也可以。
video_detection就是做的视频的。

邮箱的话，outlook邮箱我正在用的。
另外，提issue请尽量在标题中体现一下大致内容，要不不好分辨issue
