### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by 1234273** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#18]
请问作者能不能方便提供一下视频检测的相关论文（不包括摄像头）呢

**Comment by PengfeiM** [comment]
你是需要我参考的论文吗？还是？

**Comment by 1234273** [comment]
如果可以的话可以分享一下毕业设计论文嘛，不方便的话可以分享一下参考的论文嘛，谢谢啦

**Comment by PengfeiM** [comment]
好的，我回去找找



发自我的小米手机
在 1234273 ***@***.***>，2021年8月23日 14:56写道：

如果可以的话可以分享一下毕业设计论文嘛，不方便的话可以分享一下参考的论文嘛，谢谢啦

**Comment by 1234273** [comment]
好滴谢谢啦

**Comment by PengfeiM** [comment]
________________________________
发件人: 1234273 ***@***.***>
发送时间: 2021年8月23日 16:03
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: PengfeiM ***@***.***>; Comment ***@***.***>
主题: Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 论文 (#18)


好滴谢谢啦

―

**Comment by 1234273** [comment]
打扰一下，请问你是回复了什么嘛，我这里只显示了一条横线

**Comment by PengfeiM** [comment]
发件人: 1234273 ***@***.***>
发送时间: 2021年8月24日 14:37
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: PengfeiM ***@***.***>; Comment ***@***.***>
主题: Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 论文 (#18)


打扰一下，请问你是回复了什么嘛，我这里只显示了一条横线

**Comment by PengfeiM** [comment]
重新发了一遍，看一下。之前可能是文件同步的问题

**Comment by 1234273** [comment]
还是没有哎，请问方便发到邮箱嘛，283116773@qq.com

**Comment by aasdfgtreh111** [comment]
收到啦，谢谢你！
