### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by Liulin12345654** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#20]
请问可以分享一下论文吗

**Comment by Axis-hcy** [comment]
请问大佬可以分享一下论文吗？3108148008@qq.com

**Comment by deng150** [comment]
请问可以分享下论文吗，1402144947@qq.com

**Comment by Chilliming** [comment]
大佬可以分享下论文吗，我的邮箱2662865374@qq.com，万分感谢。

**Comment by Cu-Cen** [comment]
大佬可以分享下论文吗，我的邮箱cucen1027@gmail.com，万分感谢。

**Comment by shanshanhao** [comment]
大佬可以分享下论文吗，我的邮箱2238374258@qq.com，万分感谢。

**Comment by BeiZhang1209** [comment]
请问可以分享一下论文嘛，我的邮箱1214091879@qq.com，谢谢！！！

**Comment by Richard88888** [comment]
请问可以分享一下论文嘛，我的邮箱843758993@qq.com，谢谢！！！

**Comment by wuzhiqiao** [comment]
求论文，1403156535@qq.com,感谢！！

**Comment by PengfeiM** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年1月18日 23:58
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 论文 (Issue #20)


***@***.******@***.***>,感谢！！

―

**Comment by Sugammer** [comment]
大佬可以分享下论文吗，想要学习下疲劳驾驶相关知识，我的邮箱1747587185@qq.com，万分感谢您！

**Comment by Sundamasaki** [comment]
大佬可以分享下论文吗，想要学习下疲劳驾驶相关知识，我的邮箱 478449750@qq.com，万分感谢您！

**Comment by PengfeiM** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年1月11日 13:49
收件人: ***@***.***>
抄送: Ma ***@***.***>; State ***@***.***>
主题: Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 论文 (Issue #20)


大佬可以分享下论文吗，想要学习下疲劳驾驶相关知识，我的邮箱 ***@***.******@***.***>，万分感谢您！

―

**Comment by Bright-MoonBeam** [comment]
大佬可以分享一下论文吗，我目前在进行相关项目，想参考一下您的项目思路，我的邮箱是2973570030@qq.com，非常感谢您！

**Comment by Cptbtptpy** [comment]
大佬可以分享一下论文吗，我的邮箱是yzb_1998@163.com，非常感谢您！

**Comment by wu-user-616** [comment]
大佬可以分享一下论文吗，我的邮箱是whr1037227@qq.com,非常感谢您！
