### ISSUE TITLE
关于尺寸不匹配

### ISSUE THREAD

**Issue by ZeyuLii** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#21]
您好
我在尝试微调网络的过程中发现在`Test.py`中使用`ssd_voc_5000.pth`配置文件的过程中会出现模型不匹配的报错信息，即
```
size mismatch for module.feature_map_conf_1.0.weight: 
copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 512, 3, 3]).
```

我注意到，您在`Test.py`中本来使用了`ssd_voc_5000_plus.pth` 这一配置，但通过您所列举的渠道无法获得，请问这一问题可以如何解决呢

感谢

**Comment by PengfeiM** [comment]
建议修改图片尺寸方面的代码。   这个test我记得是我用来测试某个训练好的模型的，可能后满没用也就没改了。  可以自己修改一下代码重新训练一下网络。
