### ISSUE TITLE
您好，请问关于训练集添加准确率与召回率应该如何添加？

### ISSUE THREAD

**Issue by chuxueze99** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#24]
关于准确率与召回率的添加字段是需要我自主添加，还是可以引用代码中已经写好，但未展示的呢？

**Comment by PengfeiM** [comment]
这里的添加字段是添加到哪里？

**Comment by Sundamasaki** [comment]
> 

你好，请问您这个问题解决了吗，想咨询一下您相关的问题，冒昧留下我的qq号

**Comment by Sundamasaki** [comment]
> 关于准确率与召回率的添加字段是需要我自主添加，还是可以引用代码中已经写好，但未展示的呢？

你好，请问您这个问题解决了吗，想咨询一下您相关的问题，冒昧留下我的qq号478449750
