### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Fanzh1234** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#26]
你好！你的这个代码必须在有英伟达显卡的电脑上跑吗？我的电脑是mac，显卡是AMD的，不支持CUDA，能跑吗？

**Comment by PengfeiM** [comment]
用GPU的话，要CUDA，所以必须N卡。
用CPU的话无所谓，但是会慢很多。
A卡深度学习有没有什么支持我不清楚

发件人: Fanzh1234 ***@***.***>
发送时间: 2022年3月16日 22:07
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 一个问题 (Issue #26)


你好！你的这个代码必须在有英伟达显卡的电脑上跑吗？我的电脑是mac，显卡是AMD的，不支持CUDA，能跑吗？
