### ISSUE TITLE
你好，请教一下

### ISSUE THREAD

**Issue by ffffffree** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#30]
如果想要改用更高版本的pytorch，需要修改哪里的代码呢？服务器的cuda版本太高，不支持1.0的pytorch了。

**Comment by PengfeiM** [comment]
你可以参考一下这个，应该改动不会太大。
***@***.***


***@***.***
发件人: ffffffree ***@***.***>
发送时间: 2022年4月7日 20:33
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30)


如果想要改用更高版本的pytorch，需要修改哪里的代码呢？服务器的cuda版本太高，不支持1.0的pytorch了。

**Comment by ffffffree** [comment]
不会意思，没太明白你的意思，不就是这个项目用的是pytorch1.0嘛？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengfeiM/Fatigue-Driven-Detection-Based-on-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30)





 你可以参考一下这个，应该改动不会太大。 
 ***@***.*** 
 
 
 ***@***.*** 
 发件人: ffffffree ***@***.***&gt; 
 发送时间: 2022年4月7日 20:33 
 收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***&gt; 
 抄送: Subscribed ***@***.***&gt; 
 主题: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30) 
 
 
 如果想要改用更高版本的pytorch，需要修改哪里的代码呢？服务器的cuda版本太高，不支持1.0的pytorch了。

**Comment by ffffffree** [comment]
谢谢你！！！

**Comment by ffffffree** [comment]
请问一下，这个项目用的是什么数据集呀

**Comment by xzqszs** [comment]
你好，请问可以有偿帮忙下载代码、配置环境以及后续调试让代码成功运行吗？本科毕设打算写这个但是我不会弄，孩子要崩溃了

**Comment by PengfeiM** [comment]
我自己用labelImg制作的。提供链接了。

发件人: ffffffree ***@***.***>
发送时间: 2022年4月8日 17:18
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: Ma Pengfei ***@***.***>; Comment ***@***.***>
主题: Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30)


请问一下，这个项目用的是什么数据集呀

**Comment by ffffffree** [comment]
好的 非常感谢

**Comment by YanbinQin** [comment]
你好  请问一下  因为pytorch版本太高问题解决了吗？

**Comment by PengfeiM** [comment]
> 你好 请问一下 因为pytorch版本太高问题解决了吗？

我没具体测试，因为最近没这个环境。 
你可以参考上面的方案。
他们大概就是换了一个函数就行了。
这种问题在版本更迭中很常见，有些函数有了更好的替代品，本身就被禁用了。

**Comment by ffffffree** [comment]
![image](https://user-images.githubusercontent.com/103193147/163956893-14c19486-6e18-4c05-8a4c-ec912fa1eb00.png)
你好，在跑camera_detection的时候出现这个错误..请问应该怎么调试呢

**Comment by YanbinQin** [comment]
> 

你可以把上面因为版本太高的问题解决 发我一份吗

**Comment by YanbinQin** [comment]
> ![image](https://user-images.githubusercontent.com/103193147/163956893-14c19486-6e18-4c05-8a4c-ec912fa1eb00.png) 你好，在跑camera_detection的时候出现这个错误..请问应该怎么调试呢

你可以把因为版本太高的解决办法给我copy一份吗

**Comment by ffffffree** [comment]
不好意思 我换了个低版本的服务器 高版本的我没去解决


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengfeiM/Fatigue-Driven-Detection-Based-on-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30)





  
 你好，在跑camera_detection的时候出现这个错误..请问应该怎么调试呢
  
你可以把因为版本太高的解决办法给我copy一份吗

**Comment by zhousiii** [comment]
请问你们有这个错误吗，怎么解决呢？TypeError: forward() missing 1 required positional argument: 'prior_data'

**Comment by PengfeiM** [comment]
该问题已经解决。参见readme

**Comment by YanbinQin** [comment]
可以把 因为pytorch版本太高问题解决 的问题解决办法 发我一份吗？谢谢


------------------------------------------------------------------
发件人：ffffffree ***@***.***>
发送时间：2022年4月19日(星期二) 16:14
收件人：PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄　送：HeYi ***@***.***>; Comment ***@***.***>
主　题：Re: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] 你好，请教一下 (Issue #30)

[image]
 你好，在跑camera_detection的时候出现这个错误..请问应该怎么调试呢
