### ISSUE TITLE
请问SSD定位人脸之后，如何得出眼部嘴部特征？

### ISSUE THREAD

**Issue by yun189** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#34]
初学者，原理的地方没看懂，请问 怎么得出眼睛和嘴部开闭状态的？

**Comment by PengfeiM** [comment]
啊这，我是直接把不同状态的眼镜和嘴巴当成不同目标来检测的

**Comment by yun189** [comment]
谢谢，现在我理解的是数据集标记的时候就打了open-eye、close-eye、open-mouth、close-mouth，ssd实际上检测的是四种目标，然后看open或者close出现的频率，在video-detection里直接判断出perclos和眨眼打哈欠？

**Comment by yun189** [comment]
还有一个问题没搞明白，bus_dataset里的accuracy是在哪里算出来的？想画loss和accuracy图，还有PR图，求指点。

**Comment by PengfeiM** [comment]
> 谢谢，现在我理解的是数据集标记的时候就打了open-eye、close-eye、open-mouth、close-mouth，ssd实际上检测的是四种目标，然后看open或者close出现的频率，在video-detection里直接判断出perclos和眨眼打哈欠？
> 

对的

**Comment by PengfeiM** [comment]
> 还有一个问题没搞明白，bus_dataset里的accuracy是在哪里算出来的？想画loss和accuracy图，还有PR图，求指点。

这个的话可以让你的训练程序每隔一定得iter或者其他参数保存一下模型，用模型跑一下测试集就行了。

**Comment by Sundamasaki** [comment]
> 还有一个问题没搞明白，bus_dataset里的accuracy是在哪里算出来的？想画loss和accuracy图，还有PR图，求指点。
哥，你好，可以请教一下您这些网络性能的图是怎么画的吗？冒昧留下我的QQ：478449750

**Comment by Sundamasaki** [comment]
> 还有一个问题没搞明白，bus_dataset里的accuracy是在哪里算出来的？想画loss和accuracy图，还有PR图，求指点。

请问您这些图画出来了吗，可不可以分享一下，孩子写论文要用到，没时间跑了，冒昧留下我的邮箱478449750@qq.com
